# Generated by Django 4.0.1 on 2022-02-22 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0005_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient_show',
            fields=[
                ('ingredient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ingredients.ingredient')),
            ],
            bases=('ingredients.ingredient',),
        ),
    ]
