# Generated by Django 4.0.1 on 2022-02-22 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0006_ingredient_show'),
        ('recipes', '0007_alter_recipe_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quantity',
        ),
    ]
