# Generated by Django 4.0.1 on 2022-02-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0007_delete_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient_int',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='ingredient_show',
            name='ingredient_ptr',
        ),
    ]
