# Generated by Django 4.0.1 on 2022-02-23 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0008_ingredient_int_remove_ingredient_show_ingredient_ptr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredient_int',
        ),
        migrations.DeleteModel(
            name='Ingredient_show',
        ),
    ]
