# Generated by Django 4.0.1 on 2022-02-04 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0003_logs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='Receipe',
        ),
    ]
