# Generated by Django 4.0.1 on 2022-02-05 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0004_rename_location_receipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipe',
            old_name='city',
            new_name='ingredients',
        ),
        migrations.RenameField(
            model_name='receipe',
            old_name='country',
            new_name='name',
        ),
    ]
