# Generated by Django 4.0.1 on 2022-02-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0005_rename_city_receipe_ingredients_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('telephone', models.IntegerField()),
                ('active', models.BooleanField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Receipe',
        ),
    ]
