# Generated by Django 4.0.1 on 2022-02-16 19:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('distributors', '0006_distributor_delete_receipe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Logs',
            new_name='Logs_Distributors',
        ),
    ]
