# Generated by Django 4.0.1 on 2022-02-18 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0004_alter_ingredient_quantity'),
        ('recipes', '0002_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='quantity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ingredients.ingredient'),
            preserve_default=False,
        ),
    ]
