# Generated by Django 4.0.1 on 2022-02-21 01:00

from django.db import migrations, models
import ingredients.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='quantity',
            field=models.IntegerField(verbose_name=ingredients.models.Ingredient),
        ),
    ]
