# Generated by Django 4.0.1 on 2022-02-21 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0004_alter_ingredient_quantity'),
        ('recipes', '0004_alter_recipe_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, height_field=10, null=True, upload_to='uploads/', width_field=10),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='quantity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.ingredient'),
        ),
    ]
