# Generated by Django 4.0.1 on 2022-02-22 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0008_ingredient_int_remove_ingredient_show_ingredient_ptr'),
        ('recipes', '0007_alter_recipe_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='quantity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.ingredient'),
        ),
    ]
